package com.blackrubystudio.aipel3.db;

/**
 * Created by daniel on 17. 1. 6.
 */

public class Models {

    public static final String EXPENSE = "CREATE TABLE IF NOT EXISTS expense (_ID INTEGER PRIMARY KEY AUTOINCREMENT, CATEGORY TEXT, PLACE TEXT, PRICE INTEGER, _DATE INTEGER, _TIME INTEGER, CATEGORYNUM INTEGER)";
    public static final String BUDGET = "CREATE TABLE IF NOT EXISTS budget (_ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT, IS_GOAL INTEGER, CURRENT_BUDGET INTEGER, TARGET_BUDGET INTEGER, DUE_DATE INTEGER, MONTHLY_BUDGET INTEGER)";

}